//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HalloWCF.Client.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Kuchen", Namespace="http://schemas.datacontract.org/2004/07/HalloWCF.Host")]
    [System.SerializableAttribute()]
    public partial class Kuchen : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DruchmesserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MyPropertyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Druchmesser {
            get {
                return this.DruchmesserField;
            }
            set {
                if ((this.DruchmesserField.Equals(value) != true)) {
                    this.DruchmesserField = value;
                    this.RaisePropertyChanged("Druchmesser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MyProperty {
            get {
                return this.MyPropertyField;
            }
            set {
                if ((this.MyPropertyField.Equals(value) != true)) {
                    this.MyPropertyField = value;
                    this.RaisePropertyChanged("MyProperty");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetWochentag", ReplyAction="http://tempuri.org/IService1/GetWochentagResponse")]
        string GetWochentag();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetWochentag", ReplyAction="http://tempuri.org/IService1/GetWochentagResponse")]
        System.Threading.Tasks.Task<string> GetWochentagAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetKuchen", ReplyAction="http://tempuri.org/IService1/GetKuchenResponse")]
        HalloWCF.Client.ServiceReference1.Kuchen[] GetKuchen();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetKuchen", ReplyAction="http://tempuri.org/IService1/GetKuchenResponse")]
        System.Threading.Tasks.Task<HalloWCF.Client.ServiceReference1.Kuchen[]> GetKuchenAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : HalloWCF.Client.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<HalloWCF.Client.ServiceReference1.IService1>, HalloWCF.Client.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public string GetWochentag() {
            return base.Channel.GetWochentag();
        }
        
        public System.Threading.Tasks.Task<string> GetWochentagAsync() {
            return base.Channel.GetWochentagAsync();
        }
        
        public HalloWCF.Client.ServiceReference1.Kuchen[] GetKuchen() {
            return base.Channel.GetKuchen();
        }
        
        public System.Threading.Tasks.Task<HalloWCF.Client.ServiceReference1.Kuchen[]> GetKuchenAsync() {
            return base.Channel.GetKuchenAsync();
        }
    }
}
